name: CI - Build and publish Mule App

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
      ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
      ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORG_ID }}
      ANYPOINT_ENV: ${{ secrets.ANYPOINT_ENV }}   # e.g., Sandbox, Dev, Prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache maven dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Mule application
        run: mvn clean package -DmuleDeploy

      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli-v4

      - name: Authenticate with Anypoint
        run: |
          anypoint-cli-v4 --username="${{ env.ANYPOINT_CLIENT_ID }}" \
                          --password="${{ env.ANYPOINT_CLIENT_SECRET }}" \
                          --organization="${{ env.ANYPOINT_ORG_ID }}" \
                          --environment="${{ env.ANYPOINT_ENV }}" \
                          config set default

      - name: Deploy Mule application to CloudHub
        run: |
          APP_NAME=my-mule-app
          JAR_FILE=target/*.jar
          
          anypoint-cli-v4 runtime-mgr cloudhub-application deploy $APP_NAME $JAR_FILE \
            --workers 1 \
            --workerSize MICRO \
            --region us-east-1 \
            --runtime 4.4.0 \
            --replicas 1 \
            --persistent-queue false \
            --update
