name:  CI - Build and publish Mule App

on: 
  push: 
    branches :
      - main
    workflow_dispatch: {}

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
       ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
      ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: '17'

        - name: Cache maven dependencies
          uses: actions/cache@v4
          with:
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2

          - name: Build & Deploy to excahnge
            run: mvn -B clean deploy -Dskiptest
          
