name: CI - Build & Publish Mule App to Exchange

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
      ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}
      ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORG_ID }}
      ANYPOINT_ENV_ID: ${{ secrets.ANYPOINT_ENV_ID }}

    steps:
      # 1) Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3) Cache Maven repo
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 4) Create Maven settings.xml
      - name: Write Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << 'EOF'
          <settings>
            <servers>
              <server>
                <id>anypoint-exchange</id>
                <username>${ANYPOINT_CLIENT_ID}</username>
                <password>${ANYPOINT_CLIENT_SECRET}</password>
              </server>
            </servers>
          </settings>
          EOF

      # 5) Build & Publish to Exchange
      - name: Build & Publish to Exchange
        run: |
          mvn -B clean deploy -DskipTests \
            -Danypoint.org=${{ secrets.ANYPOINT_ORG_ID }} \
            -Danypoint.env=${{ secrets.ANYPOINT_ENV_ID }}
